app = "trading-engine-serhii"
primary_region = "fra"

[vm]
  memory = "512mb"

[env]
  PORT = "8501"  # Changed from 8000 to 8501 (Streamlit's port)
  UVICORN_WORKERS = "1"
  UVICORN_LIMIT_MAX_REQUESTS = "1000"
  UVICORN_TIMEOUT_KEEP_ALIVE = "30"

[[services]]
  internal_port = 8501  # Changed from 8000 to 8501 (Streamlit's port)
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.http_checks]
    interval = 10000
    grace_period = "5s"
    timeout = 2000
    restart_limit = 3

    [[services.http_checks.http]]
      path = "/"  # Changed from "/health" to "/" (Streamlit's root)
      method = "get"
      protocol = "http"
      tls_skip_verify = false

      [services.http_checks.http.headers]
        Content-Type = "application/json"
