class LocalStorage:
    def __init__(self) -> None: ...
    def getItem(self, key: str) -> str: ...
    def setItem(self, key: str, value: str) -> None: ...
    def removeItem(self, key: str) -> None: ...