apiVersion: v1
kind: Service
metadata:
  name: trading-engine-service
spec:
  selector:
    app: trading-engine
  ports:
  - name: api
    port: 8000
    targetPort: 8000
  - name: dashboard
    port: 8501
    targetPort: 8501
  type: LoadBalancer